#!/bin/python3 
import os
import threading

# Функция для запуска программы
def run_program(program):
    while True:
        os.system(program)

# Список программ для запуска
programs = ["opera-proxy", "audiosource run"]

# Создание потоков для каждой программы
threads = []
for program in programs:
    thread = threading.Thread(target=run_program, args=(program,))
    thread.start()
    threads.append(thread)

# Ожидание завершения всех потоков
for thread in threads:
    thread.join()

print("Все программы успешно запущены.")