#!/bin/python3
import subprocess
import os
import time
import docker
from threading import Thread


def get_container_id(name):
    client = docker.from_env()
    containers = client.containers.list(all=True)
    for container in containers:
        if container.name == name:
            return container.id[:12]
    return None


def NyakaStarter():
    print('Вход в NyakaStarter')
    while True:
        os.system('python3 /home/mrmoder/genshin-impact-offline/NyakaChan/main.py')
        time.sleep(20)


gio_docker_names = ['32_dev-redis-1', '32_dev-mysql-1', '32_dev-sdk-1', '32_dev-adminer-1', '32_dev-dispatch-1', '32_dev-phpmyadmin-1',
                    '32_dev-nodeserver-1', '32_dev-dbgate-1', '32_dev-gateserver-1', '32_dev-multiserver-1', '32_dev-muipserver-1', '32_dev-gameserver-1']
containers = []
NyakaChan = True


result = subprocess.run("whoami", shell=True, capture_output=True, text=True)
output = result.stdout.strip() if result.stdout else result.stderr.strip()


if output != "root":
    print('Эту команду можно выполнить только от имени Root')
else:
    print('Начинаю поиск процесса autostart-script...')
    while_break = False
    while True:
        if while_break == True:
            break
        process = subprocess.Popen(
            ['ps', 'aux'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, _ = process.communicate()
        stdout = stdout.decode()

        for line in stdout.split('\n'):
            if line:
                parts = line.split()
                # print(
                #     f'ID процесса: {parts[1]}, Имя: {parts[10]}, Аргументы: {" ".join(parts[11:])}')
                if " ".join(parts[11:]) == "/usr/local/bin/autostart-script":
                    print("Нашёл процесс autostart-script!")
                    while_break = True
                    break
    time.sleep(60 * 5)
    os.system('zerotier-one -d &')
    os.system('dockerd &')
    while True:
        try:
            client = docker.from_env()
            for i in gio_docker_names:
                containers.append(get_container_id(i))
            # print(containers)
            for container_id in containers:
                container = client.containers.get(container_id)
                # print(f"{container.name} {container.status}")
                if container.status != "running":
                    os.system("""
                    cd /home/mrmoder/genshin-impact-offline/server-docker-configs/3.2_dev/
                    pwd
                    nice -n 19 ./start.sh
                    """)
        except Exception as e:
            print(f"Ошибка: {e}")
            os.system("""
                    cd /home/mrmoder/genshin-impact-offline/server-docker-configs/3.2_dev/
                    pwd
                    nice -n 19 ./start.sh
                    """)
        time.sleep(20)
        if NyakaChan == True:
            th = Thread(target=NyakaStarter)
            th.start()
            NyakaChan = False
        containers.clear()
